version: '3'

services:
  php:
    build: ./docker/php
    container_name: miniblog-php
    volumes:
    - .:/sync
    ports:
    - 8000:8000
    working_dir: /sync/backend
    command: php -S 0.0.0.0:8000 -t public

  nuxt:
    build: ./docker/nuxt 
    container_name: miniblog-nuxt
    volumes:
    - .:/sync
    ports:
    - 3000:3000
    working_dir: /sync/frontend
    command: bash -c "yarn && yarn run dev -H 0.0.0.0 -p 3000"
  
  nginx:
    image: nginx
    container_name: miniblog-nginx
    ports:
    - 80:80
    volumes:
    - .:/sync
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php
  
  db:
    image: mysql:5.7
    container_name: miniblog-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: miniblog
      MYSQL_USER: miniblog
      MYSQL_PASSWORD: miniblog
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    #- ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    #- ./docker/db/sql:/docker-entry-point-initdb.d
    ports:
    - 3306:3306