version: '3'

services:
  php:
    image: miniblog/php
    container_name: miniblog-php
    #build: ./docker/php
    volumes:
    - .:/sync

  nuxt:
    image: miniblog/nuxt    
    container_name: miniblog-nuxt
    command: node server.js
    volumes:
    - .:/sync
  
  nginx:
    image: nginx
    container_name: miniblog-nginx
    ports:
    - 80:80
    volumes:
    - .:/sync
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php
  
  db:
    image: mysql:5.7
    container_name: miniblog-db-host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: miniblog
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entry-point-initdb.d
    ports:
    - 3306:3306